services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 30

  app:
    build:
      context: .
      image: stress-test
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped

  tests:
    build:
      context: .
      target: builder
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    command: sh -c "go test ./... -v"


